// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillsHub.Persistence;

#nullable disable

namespace SkillsHub.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240604003232_add_log_to_lesson")]
    partial class addlogtolesson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SkillsHub.Domain.BaseModels.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EnglishLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnHashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFindCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UserStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SkillsHub.Domain.BaseModels.BaseUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("BaseUserInfo");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.AgeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AgeTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.ApplicationUserBaseUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseUserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BaseUserInfoId");

                    b.ToTable("ApplicationUserBaseUserInfo");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.ExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseUserInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BaseUserInfoId");

                    b.ToTable("ExternalConnections");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.FinanceElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(15, 4)
                        .HasColumnType("decimal(15,4)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLateDateStart")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPermanentStaffGroup")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnlimitedLessonsCount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResultLessonsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PaymentCategoryId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupStudent", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId", "StudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ParentGroupId", "ParentStudentId");

                    b.ToTable("GroupStudents");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupTeacher", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ParentGroupId", "ParentTeacherId");

                    b.ToTable("GroupTeachers");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaximumStudents")
                        .HasColumnType("int");

                    b.Property<int>("MinimumStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("GroupTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalMaterials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCompletedByTeacher")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsСompleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LessonTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkToWebinar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LessonTaskId");

                    b.HasIndex("ParentId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonStudent", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VisitStatus")
                        .HasColumnType("int");

                    b.HasKey("LessonId", "StudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ParentLessonId", "ParentStudentId");

                    b.ToTable("LessonStudents");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CheckAgeType")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckGroupType")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationTypeValue")
                        .HasColumnType("int");

                    b.Property<string>("FrequencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgeTypeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParentId");

                    b.ToTable("LessonTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonTypePaymentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("PaymentCategoryId");

                    b.ToTable("LessonTypePaymentCategories");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonTypeStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonTypeStudents");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonTypeTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LessonTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonTypeTeachers");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.NotInUse.LessonTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LessonTasks");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequest")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("NotificationMessages");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.NotificationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationUsers");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.PaymentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("DurationTypeStudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationTypeStudentValue")
                        .HasColumnType("int");

                    b.Property<string>("DurationTypeTeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationTypeTeacherValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MinCountLessonsToPay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StudentPrice")
                        .HasPrecision(15, 4)
                        .HasColumnType("decimal(15,4)");

                    b.Property<decimal>("TeacherPrice")
                        .HasPrecision(15, 4)
                        .HasColumnType("decimal(15,4)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("PaymentCategories");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.RequestLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LessonBeforeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NewEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NewStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonBeforeId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLessons");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.WorkingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayName")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("EndDate")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RepeatIntervalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepeatIntervalValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartDate")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("WorkingEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("WorkingStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("DaySchedules");

                    b.HasDiscriminator<string>("Discriminator").HasValue("WorkingDay");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SkillsHub.Persistence.LessonTeacher", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonId", "TeacherId");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.HasIndex("ParentLessonId", "ParentTeacherId");

                    b.ToTable("LessonTeachers");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupWorkingDay", b =>
                {
                    b.HasBaseType("SkillsHub.Domain.Models.WorkingDay");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("GroupId");

                    b.HasDiscriminator().HasValue("GroupWorkingDay");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.UserWorkingDay", b =>
                {
                    b.HasBaseType("SkillsHub.Domain.Models.WorkingDay");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ApplicationUserId");

                    b.HasDiscriminator().HasValue("UserWorkingDay");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillsHub.Domain.BaseModels.BaseUserInfo", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.BaseUserInfo", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.AgeType", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.AgeType", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.ApplicationUserBaseUserInfo", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "ApplicationUser")
                        .WithMany("ConnectedUsersInfo")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.BaseModels.BaseUserInfo", "BaseUserInfo")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("BaseUserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("BaseUserInfo");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Course", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Course", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.ExternalConnection", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", null)
                        .WithMany("ExternalConnections")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SkillsHub.Domain.BaseModels.BaseUserInfo", null)
                        .WithMany("ExternalConnections")
                        .HasForeignKey("BaseUserInfoId");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.FinanceElement", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.FinanceElement", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("SkillsHub.Domain.Models.Student", null)
                        .WithMany("FinanceElements")
                        .HasForeignKey("StudentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Group", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.LessonType", "LessonType")
                        .WithMany("Groups")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.Group", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("SkillsHub.Domain.Models.PaymentCategory", "PaymentCategory")
                        .WithMany()
                        .HasForeignKey("PaymentCategoryId");

                    b.Navigation("LessonType");

                    b.Navigation("Parent");

                    b.Navigation("PaymentCategory");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupStudent", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.Student", "Student")
                        .WithMany("Groups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.GroupStudent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentGroupId", "ParentStudentId");

                    b.Navigation("Group");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupTeacher", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Group", "Group")
                        .WithMany("GroupTeachers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.Teacher", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.GroupTeacher", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentGroupId", "ParentTeacherId");

                    b.Navigation("Group");

                    b.Navigation("Parent");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupType", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.GroupType", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Lesson", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Group", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId");

                    b.HasOne("SkillsHub.Domain.Models.NotInUse.LessonTask", "LessonTask")
                        .WithMany()
                        .HasForeignKey("LessonTaskId");

                    b.HasOne("SkillsHub.Domain.Models.Lesson", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Group");

                    b.Navigation("LessonTask");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonStudent", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Lesson", "Lesson")
                        .WithMany("ArrivedStudents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.Student", "Student")
                        .WithMany("Lessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.LessonStudent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentLessonId", "ParentStudentId");

                    b.Navigation("Lesson");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonType", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.AgeType", "AgeType")
                        .WithMany("LessonTypes")
                        .HasForeignKey("AgeTypeId");

                    b.HasOne("SkillsHub.Domain.Models.Course", "Course")
                        .WithMany("LessonTypes")
                        .HasForeignKey("CourseId");

                    b.HasOne("SkillsHub.Domain.Models.GroupType", "GroupType")
                        .WithMany("LessonTypes")
                        .HasForeignKey("GroupTypeId");

                    b.HasOne("SkillsHub.Domain.Models.Location", "Location")
                        .WithMany("LessonTypes")
                        .HasForeignKey("LocationId");

                    b.HasOne("SkillsHub.Domain.Models.LessonType", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("AgeType");

                    b.Navigation("Course");

                    b.Navigation("GroupType");

                    b.Navigation("Location");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonTypePaymentCategory", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.LessonType", "LessonType")
                        .WithMany("LessonTypePaymentCategory")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.PaymentCategory", "PaymentCategory")
                        .WithMany("LessonTypePaymentCategory")
                        .HasForeignKey("PaymentCategoryId");

                    b.Navigation("LessonType");

                    b.Navigation("PaymentCategory");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonTypeStudent", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.LessonType", "LessonType")
                        .WithMany("LessonTypeStudents")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.LessonTypeStudent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("SkillsHub.Domain.Models.Student", "Student")
                        .WithMany("PossibleCources")
                        .HasForeignKey("StudentId");

                    b.Navigation("LessonType");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonTypeTeacher", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.LessonType", "LessonType")
                        .WithMany("LessonTypeTeachers")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.LessonTypeTeacher", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("SkillsHub.Domain.Models.Teacher", "Teacher")
                        .WithMany("PossibleCources")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonType");

                    b.Navigation("Parent");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Location", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Location", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.NotificationMessage", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.NotificationUser", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.NotificationMessage", "NotificationMessage")
                        .WithMany("Users")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.PaymentCategory", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.PaymentCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.RequestLesson", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Lesson", "LessonBefore")
                        .WithMany()
                        .HasForeignKey("LessonBeforeId");

                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("LessonBefore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Student", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "ApplicationUser")
                        .WithOne("UserStudent")
                        .HasForeignKey("SkillsHub.Domain.Models.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Teacher", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "ApplicationUser")
                        .WithOne("UserTeacher")
                        .HasForeignKey("SkillsHub.Domain.Models.Teacher", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SkillsHub.Persistence.LessonTeacher", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Lesson", "Lesson")
                        .WithOne("Teacher")
                        .HasForeignKey("SkillsHub.Persistence.LessonTeacher", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Domain.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillsHub.Persistence.LessonTeacher", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentLessonId", "ParentTeacherId");

                    b.Navigation("Lesson");

                    b.Navigation("Parent");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupWorkingDay", b =>
                {
                    b.HasOne("SkillsHub.Domain.Models.Group", "Group")
                        .WithMany("DaySchedules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.UserWorkingDay", b =>
                {
                    b.HasOne("SkillsHub.Domain.BaseModels.ApplicationUser", "ApplicationUser")
                        .WithMany("UserWorkingDays")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SkillsHub.Domain.BaseModels.ApplicationUser", b =>
                {
                    b.Navigation("ConnectedUsersInfo");

                    b.Navigation("ExternalConnections");

                    b.Navigation("Notifications");

                    b.Navigation("UserStudent");

                    b.Navigation("UserTeacher");

                    b.Navigation("UserWorkingDays");
                });

            modelBuilder.Entity("SkillsHub.Domain.BaseModels.BaseUserInfo", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("ExternalConnections");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.AgeType", b =>
                {
                    b.Navigation("LessonTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Course", b =>
                {
                    b.Navigation("LessonTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Group", b =>
                {
                    b.Navigation("DaySchedules");

                    b.Navigation("GroupStudents");

                    b.Navigation("GroupTeachers");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.GroupType", b =>
                {
                    b.Navigation("LessonTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Lesson", b =>
                {
                    b.Navigation("ArrivedStudents");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.LessonType", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("LessonTypePaymentCategory");

                    b.Navigation("LessonTypeStudents");

                    b.Navigation("LessonTypeTeachers");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Location", b =>
                {
                    b.Navigation("LessonTypes");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.NotificationMessage", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.PaymentCategory", b =>
                {
                    b.Navigation("LessonTypePaymentCategory");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Student", b =>
                {
                    b.Navigation("FinanceElements");

                    b.Navigation("Groups");

                    b.Navigation("Lessons");

                    b.Navigation("PossibleCources");
                });

            modelBuilder.Entity("SkillsHub.Domain.Models.Teacher", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Lessons");

                    b.Navigation("PossibleCources");
                });
#pragma warning restore 612, 618
        }
    }
}
